[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:backend]
command=npm run dev:payload
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/backend.err.log
stdout_logfile=/var/log/supervisor/backend.out.log
user=nextjs
environment=NODE_ENV=development,PORT=7118

[program:frontend]
command=npm run dev
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/frontend.err.log
stdout_logfile=/var/log/supervisor/frontend.out.log
user=nextjs
environment=NODE_ENV=development,PORT=3000,NEXT_PUBLIC_PAYLOAD_URL=http://localhost:7118
