// Generated by Payload
// This file contains the TypeScript types for your collections

declare namespace Payload {
  // Collection: Users
  export interface User {
    id: string;
    email: string;
    roles: ('admin' | 'user')[];
    updatedAt: string;
    createdAt: string;
  }

  // Collection: Media
  export interface Media {
    id: string;
    url: string;
    filename: string;
    mimeType: string;
    filesize: number;
    width?: number;
    height?: number;
    alt?: string;
    updatedAt: string;
    createdAt: string;
  }

  // Collection: Posts
  export interface Post {
    id: string;
    title: string;
    slug: string;
    content: any; // Rich text content
    image?: string | Media;
    updatedAt: string;
    createdAt: string;
  }

  // API Response Types
  export interface CollectionResponse<T> {
    docs: T[];
    totalDocs: number;
    limit: number;
    totalPages: number;
    page: number;
    pagingCounter: number;
    hasPrevPage: boolean;
    hasNextPage: boolean;
    prevPage: number | null;
    nextPage: number | null;
  }
}
